// main.js
window.$ = window.jQuery = require('../node_modules/jquery/dist/jquery.min.js');
var bootstrap = require('../node_modules/bootstrap/dist/js/bootstrap.min.js');
var bootstrap_material_design = require('bootstrap-material-design');
var ripples = require ('../node_modules/bootstrap-material-design/dist/js/ripples.js');
var angular = require('../node_modules/angular/angular.min.js');
var angular_route = require('../node_modules/angular-route/angular-route.min.js');
var animate = require ('../node_modules/angular-animate/angular-animate.min.js');
var toaster = require('../node_modules/angularjs-toaster/toaster.min.js');
var satellizer = require('../node_modules/satellizer/satellizer.min.js');
$.material.init();
//require('../css/main.css');
var app = require('./app.js');
var access_controller = require('./controller-access.js');
var index_controller = require('./controller-index.js');
var menu_controller = require('./controller-menu.js');
var add_profile = require('./controller-addprofile.js');
var profile = require('./controller-profile.js');
var forgot = require('./controller-forgot.js');
var reset = require('./controller-reset.js');
var scrollChange = require('./directive-scroll.js');
var tabs = require('./directive-tabs.js');
